general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 8, y = 8 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
bold = { style = "Bold" }
size = 12.5

[scrolling]
history = 1000
